plugins:
  daily_digest_enabled:
    default: false
    client: true
  daily_digest_category_id:
    default: ""
    client: true
  daily_digest_tag:
    default: "daily-digest"
    client: true
  news_api_key:
    default: ""
    client: true
  openai_api_key:
    default: ""
    client: true
  openai_model:
    default: "gpt-4o"
    client: true
  openai_temperature:
    default: 0.7
    client: true
