plugins:
  daily_digest_enabled:
    default: false
    client: true
  daily_digest_category_id:
    default: ""
    client: true
  daily_digest_tag:
    default: "daily-digest"
    client: true
  daily_digest_post_time:
    default: "09:00"
    client: true
  newsapi_api_key:
    default: ""
    client: true
